local Deserializer = require("Deserializer")
local Serializer   = require("Serializer")
local VMTemplate   = require("VMTemplate")

local Obfuscator = {}

-- This will Shuffle a string's chars using Fisher-Yates seeded xorshift --
local function seededShuffle(s, seed)
    local chars = {}
    for i = 1, #s do chars[i] = s:sub(i, i) end
    local state = seed
    local function next()
        state = (state * 1664525 + 1013904223) % 4294967296
        return state
    end
    for i = #chars, 2, -1 do
        local j = (next() % i) + 1
        chars[i], chars[j] = chars[j], chars[i]
    end
    return table.concat(chars)
end

-- And Generate a random-looking variable name from a seed --
local function genVarName(seed, length)
    local charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    local shuffled = seededShuffle(charset, seed)
    local name = {}
    local state = seed
    for i = 1, length do
        state = (state * 6364136223846793005 + 1442695040888963407) % 4294967296
        name[i] = shuffled:sub((state % #shuffled) + 1, (state % #shuffled) + 1)
    end
    return table.concat(name)
end

-- Wrap hex string into line-folded string literal --
local function foldHex(hex, width)
    width = width or 78
    local lines = {}
    for i = 1, #hex, width do
        lines[#lines+1] = '"' .. hex:sub(i, i + width - 1) .. '"'
    end
    return table.concat(lines, "..\n    ")
end

function Obfuscator.obfuscate(bytecodeData, options)
    options = options or {}
    local seed = options.seed or 0xDEADBEEF

    -- 1. Deserialize --
    local proto = Deserializer.decode(bytecodeData)

    -- 2. Serialize back into our own compact hex format --
    local encoded = Serializer.encode(proto)

    -- 3. Generate variable names --
    local runFnName    = genVarName(seed,           8)
    local payloadName  = genVarName(seed + 0x1234,  7)
    local envName      = genVarName(seed + 0x5678,  6)

    -- 4. Build output --
    local lines = {}

    -- VM source inline --
    lines[#lines+1] = "-- Generated by LuaObfuscator"
    lines[#lines+1] = "local " .. envName .. " = " ..
        "(getfenv or function() return _ENV end)()"
    lines[#lines+1] = ""

    -- Inject VM --
    lines[#lines+1] = VMTemplate.source

    -- Payload --
    lines[#lines+1] = "local " .. payloadName .. " ="
    lines[#lines+1] = "    " .. foldHex(encoded)
    lines[#lines+1] = ""

    -- Call --
    lines[#lines+1] = string.format(
        'run(%s, %s)', payloadName, envName
    )

    return table.concat(lines, "\n")
end

return Obfuscator
